language: node_js
install:
  - npm install
script:
  - npm run lint
  - npm run test:cover
  - npm run check-coverage
after_success:
  - cat ./coverage/lcov.info | codecov
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/